[[constraint]]
  name = "github.com/coreos/etcd"
  version = "3.3.0"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.0.3"

[[constraint]]
  name = "github.com/xenolf/lego"
  version = "0.4.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
